### ISSUE TITLE
Fixed GOP segment encoding for HLS/DASH

### ISSUE THREAD

**Issue by ddorian** [master-of-zen/Av1an#106]
How would you do distributed encoding when you need to have fixed GOP, and fixed segment-time for HLS/DASH output ?

Splitting the video by I-frame isn't possible. Splitting at exact frame will return wrong results (missing I-frame). 

Any idea ?

**Comment by n9Mtq4** [comment]
I am not familiar with HLS/DASH and its requirements, but I can comment on what it takes to get Av1an to split every n frames.

Av1an is designed to split on scene cuts to minimize the efficiency loss of chunked encoding and doesn't have a method for splitting every n frames. An option would be to specify the frames in which to split on in a file separated by commas. You can specify this file with `--scenes filename`. For example, if you want to split every 100 frames for a total of m frames, create a file with `100,200,300,...,m-100`.

There is also the problem that we use ffmpeg's segment to do the splitting, which requires an I-frame on the boundary. The best option for now is to lossless encode your source with a gop of size 1 (or in your case since you know the split points ahead of time with a gop of size n) with `ffmpeg -i source.mkv -c:v libx264 -crf 0 -g n source_gop.mkv` to ensure that there will always be an I-frame. I am currently working on a patch that will add the option to use ffmpeg's [select filter](https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect) instead which should allow frame accurate splits regardless of I-frame placement.

**Comment by ddorian** [comment]
Yes, scene cuts need to be 0 (you can enable them inside segments though) in HLS.

Splitting with segment needs an I-frame so it's not doable.

Splitting on exact frame may not have the starting I-frame of the segment.

One way I was thinking is to use `-ss` to seek to different positions in the stream.  
`-ss` is frame accurate IF you also encode.
Each segment would seek to different positions of the file. Should be fast.

Or maybe splitting with segment but keeping room on both ends, and doing fancy calculations to further cut on exact frames when encoding ?

Will check how select filter may work.

**Comment by n9Mtq4** [comment]
We have added the ability to encode chunks with non-keyframe boundaries in #115 and #116.

**Comment by sridhard** [comment]
@n9Mtq4 @ddorian For HLS and DSAH we want to encode the video with fixed GOP segment. Can you please help me how you achieved it?
