### ISSUE TITLE
Request for audio passthrough & same framerate

### ISSUE THREAD

**Issue by githupper** [master-of-zen/Av1an#136]
Would like to request for the following functionalities currently present in Handbrake to be implemented when/where possible

1)  AAC\FLAC\APE\MP3 Audio Auto Passthrough - most audio are already compressed and or does not make a huge impact on space. Saves on encoding time
2) Framerate (same as source) - so that there need not be multiple profiles for different framerates

**Comment by nathanielcwm** [comment]
idk if anything has changed but audio from what I remember used to be passed through by default.

**Comment by Fuchs4** [comment]
The default --audio-params are are `-c:a copy`, which is passthrough without any reencoding. For passthrough just omit `--audio_params` or use `--audio_params "-c:a copy"`.
Framerate is also same as source by default, but av1an does not support variable framerates because it is piping to the video encoders directly, and pipes can not handle variable framerates properly. This could be fixed by using ffmpeg directly, but ffmpeg does not (yet) support all encoders which av1an supports, so it would not work with all encoders, and it might not work with all chunk methods. But variable framerates is definitively something that should be addressed.

**Comment by githupper** [comment]
Issues have been addressed. Thank you to all commenters
