### ISSUE TITLE
x265 encoder parameter causes failure

### ISSUE THREAD

**Issue by kozross** [master-of-zen/Av1an#159]
This speaks for itself:

```
[koz@Emi ~]$ av1an --input gundam-wing-01.mkv --output_file test --encoder x265 --workers 8
Invalid commands:
slow suggest: -o
If you sure in validity of your commands: use --force
```

Sometimes, 'slow suggest' gives something else (I've seen -w before, for example).

**Comment by master-of-zen** [comment]
What happens is fuzzy command validation thinks that slow preset is also a command.
@kozross try upgrading to latest pip. Also can try just to use `--force`

**Comment by kozross** [comment]
Can confirm that ``--force`` works.

**Comment by luigi311** [comment]
looks like this happens even on github actions, it also seems like that invalid commands doesnt change the exit code. @master-of-zen you might want to change the exit code to 1 or something when not using --force since the program errored out and quit without encoding. We might need to change the github actions to actually check for a file at the end of the encode to make sure it actually ran and did something.

**Comment by luigi311** [comment]
This is fixed and the new actions have been implemented. You shouldn't need to use --force anymore @kozross . Can you go ahead and mark this as closed again.
