### ISSUE TITLE
[feature request] Image sequence as input

### ISSUE THREAD

**Issue by lastrosade** [master-of-zen/Av1an#221]
Allow specifying a directory with images as input to av1an

for example --image_dir "/path/to/images_%03d.png"

**Comment by lastrosade** [comment]
Oh this is still opened. It works with vapoursynth.

**Comment by NicTanghe** [comment]
I dont want to be a necromancer but when i try to use it with exr`s it doesn`t seem to work.

mardini_2024/render/sandyMcSand
❯ av1an -x 300 -i ./SandyMcSand.%04d.EXR -w 4 -e aom -c mkvmerge --resume -m lsmash --photon-noise=10 --set-thread-affinity=2 --verbose -a " -an " -f " -an " -v " --bit-depth=10 --cpu-used=16 --end-usage=q --cq-level=24 --threads=2 --tile-columns=0 --tile-rows=0 --lag-in-frames=64 --tune-content=psy --tune=ssim --enable-keyframe-filtering=1 --disable-kf --kf-max-dist=9999 --enable-qm=1 --deltaq-mode=0 --aq-mode=0 --quant-b-adapt=1 --enable-fwd-kf=0 --arnr-strength=1 --sb-size=dynamic --enable-dnl-denoising=0 " -o output.mkv

Error: Input path "./SandyMcSand.%04d.EXR" does not exist. Please ensure you typed it properly and it has not been moved.

am i doing something wrong ?

ps. a discutions tab might be a great aditio to the github.

**Comment by master-of-zen** [comment]
I have never seen .EXR file.
I'm pretty sure it's not supported, and i recommend by any means convert to something that av1an can use as input 👍🏽

**Comment by NicTanghe** [comment]
Verry strange that you have not seen the industry standard file.

Do you know of an image formate that is lossles or losslesly compressed that has higher then 8bpc encoding ?

I`d like to be able to feed it images that are better then 8bpc. so that there isn`t anny banding and i dont have to render out intermediates in video format with another program.

Where do you think is best to submit a request for supporting this file format ? (doesnt need to support multilayer rgb  should be fine)

**Comment by master-of-zen** [comment]
The original issue got fixed by using av1an vapoursynth input.

Where vapoursynth script create video output, and takes images as input.

**Comment by NicTanghe** [comment]
I have tried messing around with it a little, it wasn`t immediatly clear. i might dig a little deeper into it.

That said i stil think being able to directly feed it images  without learning an entire python library could be a great adition.
