### ISSUE TITLE
[Errno 2] No such file or directory: '.9a300a21/log.log'

### ISSUE THREAD

**Issue by traverseda** [master-of-zen/Av1an#257]
When running command

`sudo docker run -v "$(pwd)":/videos --user $(id -u):$(id -g) -it --rm masterofzen/av1an:latest -i Season\ 1/*.mkv -enc rav1e --resume`

with  sha256:6dbbaa41060d81a69bce472383df50a889a06bdeb7d7029a3c9530d526c29bb8 docker container. I think it has something to do with the temporary file deletion?

**Comment by luigi311** [comment]
whenever i get this its usually something failing because of the video source. You can try using ffmpeg to encode the video again loselessly to x264 and only include the video stream

ffmpeg -i input.mkv -map 0:v:0 -enc libx264 -crf 0 videoonly.mkv

not sure if the command is correct but it should be something along those lines and that will create a video file with only the video in it. You can then try to encode it via the above docker command and see if it works. Its usually something funky in the video source or some other tracks like subtitles or thumbnails that av1an or pyscenedetect doesnt like.

**Comment by traverseda** [comment]
One video encodes just fine, it fails moving on to the next. If I re-run the command it works fine on the next video and the process repeats. It is possible to get through the entire folder, just one video at a time.

I think this has to do with the subfolder.

**Comment by luigi311** [comment]
hmmm ive never used av1ans folder encoding feature. i instead started working on a bash script that uses parallel to encode across multiple machines and calls av1an individually.
