### ISSUE TITLE
HDR encoding

### ISSUE THREAD

**Issue by draco1544** [master-of-zen/Av1an#667]
How i can converting an hevc with HDR source file to a vp9 or av1 video without loss the HDR ? I have tried vpx, aoe and SVT-AV1, all with 4:2:0 10 bits settings. Do you have any solution ?

**Comment by master-of-zen** [comment]
You need to specify HDR primaries and transfer characteristics like here:https://github.com/master-of-zen/Av1an/blob/master/docs/Encoders/aomenc.md#flags-used-for-most-native-10-bit-hdr-content

**Comment by draco1544** [comment]
Thank, I'm going to try that. How I can do the same thing with vp9 ?

**Comment by draco1544** [comment]
> I used https://developers.google.com/media/vp9/hdr-encoding to get some idea of the settings. Note that you need to convert between ffmpeg and vpx cli parameters to work with av1an

I can't find any way of translating this parameters into vpx parameters

**Comment by ES-Six** [comment]
I just add an example below in case this could be helpful to someone, because it was hard to discover the common HDR encoding parameters when I needed them too.

HDR parameters varies depending on the encoder used. The example below is done using SVT-AV1 encoder.

Example of HDR encode with SVT-AV1 + av1an :
```sh
av1an -i input.mkv -p 1 -w 2 -e svt-av1 -o encode.mkv -v " --rc 0 --crf 21 --preset 6 --film-grain 0 --input-depth 10 --lookahead 120 --keyint -2 --color-range 0 --color-primaries 9 --transfer-characteristics 16 --matrix-coefficients 9 -w 3840 -h 2024 --pass 0 --enable-hdr 1 --mastering-display G(0.265,0.69)B(0.15,0.06)R(0.68,0.32)WP(0.3127,0.329)L(1000.0,0.005) --content-light 897,497" -m lsmash -l ERROR -r
```

Using SVT-AV1 encoder, here are the parameters related to the HDR metadata : --enable-hdr
And here are the parameters (not directly related to HDR but used a lot) commonly found when encoding HDR videos : --content-light  AND --mastering-display

According to the SVT-AV1 documentation :
- **--enable-hdr** : Enable writing of HDR metadata in the bitstream
- **--content-light** : Set content light level in the format of "max_cll,max_fall"
- **--mastering-display** : Mastering display metadata in the format of "G(x,y)B(x,y)R(x,y)WP(x,y)L(max,min)"

Note : **--content-light** and **--mastering-display** are probably not mandatory because it depends on the metadata in the source video file, but a lot of HDR videos will contain this kind of metadata.

SVT-AV1 uses a different format for mastering display, so here is a little python script found on reddit, that allows generating the mastering-display parameter values and also useful to extract content light values from the original video file like this :

```sh
python hdrinfo.py video.mkv 
```

[hdrinfo.zip](https://github.com/master-of-zen/Av1an/files/10396269/hdrinfo.zip)
