### ISSUE TITLE
DGDecNV support

### ISSUE THREAD

**Issue by videoh** [master-of-zen/Av1an#797]
Guys, I never said you were violating my license. One of your users told me you were bundling my binaries. When I objected to that he said "no, they just have a link to it", which is fine. You can even bundle my binaries if you get my written permission, but you have to ask for it. Removing support for DGDecNV seems extreme to me but do what you want.

Donald Graft

**Comment by prefix1647** [comment]
Busybody tattle-tales who don't even know what they are talking about in the first place are the worst.

Sorry they wasted your time and made you look bad/stingy.

Glad you could clear it up. No harm no foul.

**Comment by shssoichiro** [comment]
This was the email that was sent to one of our users.

![Screenshot_2024-01-02-22-20-15-670-edit_com](https://github.com/master-of-zen/Av1an/assets/5951392/a2a7014f-c3e0-428b-9793-ed5854209259)

I thought the message was pretty clear. I'm not sorry. We'll readd support for it, but not because Donald asked, but because some of our users asked.

**Comment by prefix1647** [comment]
Your view is understandable based on the hostile tone of the e-mail. 

To me it reads like someone caught on a bad day who was deeply grumpy about being asked by a stranger to provide technical support on software that he has nothing to do with, and he misread a PR and the issue got confused by multiple people from there. Certainly he could have been gracious in his dismissal of the persons inappropriate support request, but everyone has their off days.

Just happy it's clear now, regardless of how we arrived here.

**Comment by shssoichiro** [comment]
To be completely clear, the removal was done for the purpose of avoiding any potential lawsuits. Now that we have those concerns behind us, we hope to be able to continue creating software that fulfills the needs of our users, and we are glad to have Donald's support for integrating with his package (though users will continue to be required to install DgDec libraries manually, as per the licensing agreement).

In order to fully put this drama behind us, I'll be locking this thread to prevent comments from any other users. The PR re-adding support will be merged as soon as it has an approval from one of our other maintainers.
